name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: macos-14
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to GitHub Packages
        run: ./gradlew :notifications-kmp:publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT_READ_PACKAGES: ${{ secrets.PAT_READ_PACKAGES }}
